#!/bin/bash -e
_memtester_run () {
	clear
        echo "Check memory for 128M..."
        memtester 128M 1 &> /dev/null
        echo "Check memory for 256M..."
	memtester 256M 1 &> /dev/null
        echo "Check memory for 512M..."
        memtester 512M 1 &> /dev/null
        echo "Check memory for 1024M..."
        memtester 1024M 1 &> /dev/null
        echo "Check memory for 2048M..."
        memtester 2048M 1 &> /dev/null
}

_check_memory () {
	_memtester_run
	_menu
}

_check_memory_init_process () {
        _memtester_run
        _init_process
}

_init_process () {
        clear
        echo "Please wait..."
	sleep 5
        exec /sbin/init
}

_menu () {
        while true; do
		exec 3>&1
		selection=$(dialog \
			--backtitle "System Information" \
			--title "Menu" \
			--clear \
			--no-collapse \
			--menu "Please select:" 0 0 4 \
			"1" "Display System Information" \
			"2" "Display Disk Space" \
			"3" "Display Home Space Utilization" \
			2>&1 1>&3)
		exit_status=$?
		exec 3>&-
		case $exit_status in
			$DIALOG_CANCEL)
				clear
				reboot
				exit
				;;
			$DIALOG_ESC)
				clear
				reboot
				;;
		esac
		case $selection in
			1)
				_check_memory ;;
			2)
				_check_memory_init_process ;;
			3)
				_init_process ;;
		esac
	done
}

_menu
