name: Build

on: push

jobs:
  buid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Build
        run: ./build.sh
      - name: Release
        uses: softprops/action-gh-release@master
        with:
          name: Debian MATE GParted Live ${{ env.DATE }}
          tag_name: ${{ env.DATE }}
          files: |
            output/debian-mate-gparted-live-${{ env.DATE }}.iso
            output/debian-mate-gparted-live-${{ env.DATE }}.iso.sha256
            output/debian-mate-gparted-live-${{ env.DATE }}.iso.md5
